#index:
#    path: /
#    controller: App\Controller\DefaultController::index
info2:
    path: /info2/{prenom}
    requirements: 
      prenom: '^[a-zA-Z][a-zA-Z|-]+[a-zA-Z]$'
    controller: App\Controller\NouveauClientController::info2
    methods: GET