#index:
#    path: /
#    controller: App\Controller\DefaultController::index
info:
    path: /info/{prenom}
    requirements: 
      prenom: '^[a-zA-Z][a-zA-Z|-]+[a-zA-Z]$'
    controller: App\Controller\NouveauClientController::info
    methods: GET